version: '3.9'
services:
  r-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/home/ruser:cached
    command: sleep infinity
    environment:
      - DISPLAY=${DISPLAY}
    user: ruser
    working_dir: /home/ruser/workspace
