version: '3.8'
services:
  r-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/home/ruser/workspace:cached
      - ~/.gitconfig:/home/ruser/.gitconfig:ro
    command: sleep infinity
    environment:
      - DISPLAY=${DISPLAY}
    user: ruser
    working_dir: /home/ruser/workspace
